# Codemagic build configuration
# For more information, see https://docs.codemagic.io/getting-started/yaml/

workflows:
  android-obsidian-helper-build:
    name: Android Obsidian Helper Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      android_sdk_version: "34"
      java: "11"
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_HOME" > "$CM_BUILD_DIR/local.properties"
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true
