# GitHub Actions workflow to build the Android application
# This file should be placed in: .github/workflows/android-build.yml

name: Build Android APK

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 17, which is required for modern Android builds
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # 3. Grant execute permission to the Gradle wrapper script
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. Run the build command to generate the debug APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 5. Upload the generated APK as a build artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
